[build]
  publish = "."
  command = ""

[[headers]]
  for = "/install-prophunt.command"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment; filename=install-prophunt.command"

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200
