import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const TEMPLATE_PATH = join(import.meta.dirname, '..', 'templates', 'whatsapp.txt');

let cachedTemplate = null;

function getTemplate() {
  if (!cachedTemplate) {
    cachedTemplate = readFileSync(TEMPLATE_PATH, 'utf-8');
  }
  return cachedTemplate;
}

/**
 * Build a personalized WhatsApp message from the template.
 * If contact.name is missing, removes the name greeting gracefully.
 *
 * Supported fields: nombre, zona, portal, precio, tipo, detalle
 */
export function buildMessage(contact) {
  let msg = getTemplate();

  if (contact.name) {
    msg = msg.replace('{{nombre}}', contact.name);
  } else {
    // "Hola {{nombre}}, soy" → "Hola, soy"
    msg = msg.replace(/\{\{nombre\}\},?\s*/g, '');
  }

  msg = msg.replace('{{zona}}', contact.zone || 'tu zona');
  msg = msg.replace('{{portal}}', contact.portal || 'el portal');

  // Price: format as "350.000 €" or remove placeholder
  if (contact.price) {
    const formatted = Number(contact.price).toLocaleString('es-ES') + ' €';
    msg = msg.replace('{{precio}}', formatted);
  } else {
    // "por {{precio}}. " → ". "
    msg = msg.replace(/\s*por \{\{precio\}\}/g, '');
  }

  // Property type: piso, casa, ático, etc.
  msg = msg.replace('{{tipo}}', contact.propertyType || 'vivienda');

  // Detail: a natural sentence about the property generated by Claude
  // e.g. "Los 85 m² con 3 habitaciones y terraza tienen muy buena pinta"
  if (contact.detail) {
    msg = msg.replace('{{detalle}}', contact.detail);
  } else {
    msg = msg.replace(/\s*\{\{detalle\}\}/g, '');
  }

  return msg;
}
